# k8s-manifest.yml

# --- Part 1: The Redis Database Deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: redis-db
        image: "redis:alpine"
        ports:
        - containerPort: 6379
---
# --- Part 2: The Redis Database Service ---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
  - port: 6379
    targetPort: 6379
---
# --- Part 3: The Flask Web App Deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: flask-web
        image: bkochman5/flask-docker-app 
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
# --- Part 4: The Flask Web App Service (Exposed) ---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort 
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30007 